version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: sosow0212
      MYSQL_DATABASE: investment
      MYSQL_USER: admin
      MYSQL_PASSWORD: sosow0212
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: sosow0212
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
